# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=50)),
                ('show_url', models.URLField()),
                ('latest_episode_url', models.URLField()),
            ],
        ),
    ]
