# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='latest_episode_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='latest_post_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='show_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
