# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaList', '0002_auto_20161222_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='latest_episode_url',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_url',
            field=models.URLField(max_length=300),
        ),
    ]
