# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaList', '0003_auto_20161222_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='refreshed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
